{{- if .Values.hub.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "node.hub.fullname" .}}
  labels:
    {{- include "node.labels" (dict "context" . "component" .Values.hub.name "name" .Values.hub.name) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "node.fullname" . }}
  minReplicas: {{ .Values.hub.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hub.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.hub.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hub.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.hub.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hub.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
