{{- $processedDict := dict -}}
{{- range $path, $bytes := .Files.Glob "resources/**" }}
{{- $name := base (dir $path) }}
{{- if not (hasKey $processedDict $name) -}}
{{ $_ := set $processedDict $name "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ template "vsl-chain.fullname" .}}-{{ $name }}
data:
{{ ($.Files.Glob (printf "resources/%s/*" $name)).AsConfig | indent 2 }}
---
{{- end }}
{{- end }}