apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vsl-chain.geth.fullname" .}}
stringData:
  # HTTP-RPC server
  GETH_HTTP: "true"
  GETH_HTTP_ADDR: "0.0.0.0"
  GETH_HTTP_PORT: "8545"
  GETH_HTTP_API: "web3,debug,eth,txpool,net,engine"
  GETH_HTTP_VHOSTS: "*"
  GETH_HTTP_CORSDOMAIN: "*"

  # WS-RPC server
  GETH_WS: "true"
  GETH_WS_ADDR: "0.0.0.0"
  GETH_WS_PORT: "8546"
  GETH_WS_ORIGINS: "*"
  GETH_WS_API: "web3,debug,eth,txpool,net,engine"

  # authenticated APIs
  GETH_AUTHRPC_ADDR: "0.0.0.0"
  GETH_AUTHRPC_PORT: "8551"
  GETH_AUTHRPC_JWTSECRET: "/config/jwt-secret.txt"
  GETH_AUTHRPC_VHOSTS: "*"

  GETH_DATADIR: "/data"
  GETH_VERBOSITY: "3"
  GETH_NODISCOVER: "true"
  GETH_MAXPEERS: "0"
  GETH_ROLLUP_DISABLETXPOOLGOSSIP: "true"
  
  # Allow for unprotected (non EIP155 signed) transactions to be submitted via RPC
  GETH_RPC_ALLOW_UNPROTECTED_TXS: "true"
  GETH_SYNCMODE: "full"

  # Blockchain garbage collection mode, only relevant in state.scheme: hash ("full","archive")
  GETH_GCMODE: "archive"

  # metrics collection and reporting
  GETH_METRICS: "true"
  GETH_METRICS_ADDR: "0.0.0.0"
  GETH_METRICS_PORT: "7300"

  GETH_NETWORKID: "2331"
  GENESIS_FILE_PATH: "/config/genesis.json"