apiVersion: v1
kind: Secret
metadata:  
  name: {{ template "vsl-chain.proposer.fullname" .}}-signer
  annotations:
    avp.kubernetes.io/path: "kv/data/network/chain"
stringData:
  PORT: "3000"
  GCP_PROJECT_ID: "<PROPOSER_SIGNER_PROJECT_ID>"
  GCP_LOCATION_ID: "<PROPOSER_SIGNER_LOCATION_ID>"
  GCP_KEY_RING_ID: "<PROPOSER_SIGNER_KEY_RING_ID>"
  GCP_KEY_ID: "<PROPOSER_SIGNER_KEY_ID"
  GCP_KEY_VERSION: "<PROPOSER_SIGNER_KEY_VERSION>"
  ALLOWED_ADDRESSES: "<PROPOSER_SIGNER_ALLOWED_ADDRESSES>"